### ISSUE TITLE
Uploading issue when bucket region is eu

### ISSUE THREAD

**Issue by fteotini** [LevelbossMike/ember-deploy-s3#12]
I've creted two buckets, one on eu-ireland and the other on eu-frankfurt. Both have problems
The former stucks on `uploading assets...` and the latter fails with this

```
Unable to sync: InvalidRequest: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
    at Request.extractError (/frontend/node_modules/ember-deploy/node_modules/s3/node_modules/aws-sdk/lib/services/s3.js:343:35)
    at Request.callListeners (/frontend/node_modules/ember-deploy/node_modules/s3/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
    at Request.emit (/frontend/node_modules/ember-deploy/node_modules/s3/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/frontend/node_modules/ember-deploy/node_modules/s3/node_modules/aws-sdk/lib/request.js:604:14)
    at Request.transition (/frontend/node_modules/ember-deploy/node_modules/s3/node_modules/aws-sdk/lib/request.js:21:12)
    at AcceptorStateMachine.runTo (/frontend/node_modules/ember-deploy/node_modules/s3/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /frontend/node_modules/ember-deploy/node_modules/s3/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/frontend/node_modules/ember-deploy/node_modules/s3/node_modules/aws-sdk/lib/request.js:22:9)
    at Request.<anonymous> (/frontend/node_modules/ember-deploy/node_modules/s3/node_modules/aws-sdk/lib/request.js:606:12)
    at Request.callListeners (/frontend/node_modules/ember-deploy/node_modules/s3/node_modules/aws-sdk/lib/sequential_executor.js:104:18)
```

If I use a bucket creted in the us-standar region everything works smoothly, so europe is virtually excluded from this addon

**Comment by LevelbossMike** [comment]
Hi @Fed03!

This is a problem with the S3 library ember-deploy-s3 is using as it can't deal with api v4 regions. https://github.com/andrewrk/node-s3-client/issues/69 This seems to be at least problem with the frankfurt region. We will switch to use aws-sdk directly for the s3-support in the next version of ember-cli-deploy which should fix the issue. Right now the 'fix' is to just use a different region than frankfurt.

Of course this is not great but it shouldn't make a difference if you used another region because one would have a cdn in front of the assets anyway. I will add a comment about this in the readme.

**Comment by fteotini** [comment]
Thnx, and what about Ireland? Same reason?

**Comment by LevelbossMike** [comment]
If Ireland behaves messed up then maybe they switchted to v4 as well. But old regions should support the old signature protocoll

"Amazon S3 supports Signature Version 4, a protocol for authenticating inbound API requests to AWS services, in all AWS regions. At this time, existing AWS regions continue to support the previous protocol, Signature Version 2."

http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html

The bucket I am using for testing is located in Ireland and behaves fine.
